### PR TITLE
Introduce gops to webserver pkg

### LINKED ISSUE #205: use gops to report informations about gandalf
`gops` (https://github.com/google/gops)  is an agent that can report additional information about the Go process. We can use it to make easier to debug problems in `gandalf`

### PR DESCRIPTION
**Pull request by flaviamissi**
Also vendors `gops` and `osext` (gops' only dependency).

Fixes #205

### CODE REVIEW

**Comment by scorphus** [comment]
Why so many commits for a single feature?

**Comment by flaviamissi** [comment]
There's no harm in having multiple commits now that github supports "squash and merge", though I can also squash it all locally and push again. Thoughts?

**Comment by scorphus** [comment]
It depends on who chooses what to do with it as not everyone knows GH supports it – for some time now. If you don't care, who will?

**Comment by flaviamissi** [comment]
Right, I'll do it myself then, thanks for the hint.

**Comment by flaviamissi** [comment]
Thanks y'all for such a quick review! o/

**Pull request merged**
